// Torsten Sadowski
// SPDX-License-Identifier:  GPL-3.0-or-later

import { PageCallback, MakePage, MakePageCallback, SettingsPage, SettingsPageCallback } from "ui/pages.slint";
import { SideBar } from "ui/side_bar.slint";
import { UiSettings } from "ui/settings.slint";

export { PageCallback, MakePageCallback, SettingsPage, SettingsPageCallback, UiSettings }

export component App inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Slint Widgets Gallery");
    icon: @image-url("img/ring-256x256.png");

    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Slint Widgets Gallery");
            model: [@tr("Menu" => "PW"), @tr("Menu" => "Settings")];
        }

        if(side-bar.current-item == 0) : MakePage {}
        if(side-bar.current-item == 1) : SettingsPage {}
    }
}
