// Torsten Sadowski
// SPDX-License-Identifier:  GPL-3.0-or-later

import { MakePage, MakePageCallback } from "ui/make_page.slint";
import { SettingsPage, SettingsPageCallback } from "ui/settings_page.slint";
import { UiSettings } from "ui/settings.slint";
import { Page } from "ui/page.slint";

export { MakePageCallback, SettingsPage, SettingsPageCallback, UiSettings }

export component App inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("Password Maker");
    icon: @image-url("img/ring-256x256.png");

    Page { }
}
